"""empty message

Revision ID: 6e1ed40195d3
Revises: 
Create Date: 2020-05-22 00:47:19.266847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1ed40195d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ip', sa.String(length=255), nullable=True),
    sa.Column('x_coord', sa.String(length=255), nullable=True),
    sa.Column('y_coord', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registers')
    # ### end Alembic commands ###
